### ISSUE TITLE
Let Locations/Filters buttons close drawer as well

### ISSUE THREAD

**Issue by BlueSlug** [inclusive-design/covid-data-monitor#25]
## Is your feature request related to a problem?
In the narrow/mobile layout, after opening the Locations or Accessibility Filters drawers with their respective buttons, the behaviour I expected was to be able to collapse the drawer via the same button, rather than having to use the grey bar above to do so.

## Describe the solution you'd like
The buttons should toggle the drawer's state rather than only open it

## Describe alternative solutions you've considered
Having the buttons only open the drawer makes sense in other ways, such as keeping each button functionally idempotent. The requested solution may have further UX ramifications I haven't yet considered

## Additional context or notes
This is closely related to #23, and may make sense to tackle at the same time.

Screenshot to illustrate which buttons
![Screenshot_20210609-001750_cropped](https://user-images.githubusercontent.com/547933/122105145-71c77000-cde6-11eb-93f5-4d11f2c46424.png)

**Comment by amb26** [comment]
Fixed with https://github.com/inclusive-design/covid-data-monitor/pull/31
